DELETE http://localhost:3001/api/persons/3

### 
GET http://localhost:3001/api/persons
### 
POST http://localhost:3001/api/persons
Content-Type:  application/json

{
    "name": "Verdiane", 
    "number": "040-123456"
}